/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SareesRouteImport } from './routes/sarees'
import { Route as ApiFreeDataRouteImport } from './routes/api/free-data'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SareesRoute = SareesRouteImport.update({
  id: '/sarees',
  path: '/sarees',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFreeDataRoute = ApiFreeDataRouteImport.update({
  id: '/api/free-data',
  path: '/api/free-data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sarees': typeof SareesRoute
  '/api/free-data': typeof ApiFreeDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sarees': typeof SareesRoute
  '/api/free-data': typeof ApiFreeDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sarees': typeof SareesRoute
  '/api/free-data': typeof ApiFreeDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sarees' | '/api/free-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sarees' | '/api/free-data'
  id: '__root__' | '/' | '/sarees' | '/api/free-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SareesRoute: typeof SareesRoute
  ApiFreeDataRoute: typeof ApiFreeDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sarees': {
      id: '/sarees'
      path: '/sarees'
      fullPath: '/sarees'
      preLoaderRoute: typeof SareesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/free-data': {
      id: '/api/free-data'
      path: '/api/free-data'
      fullPath: '/api/free-data'
      preLoaderRoute: typeof ApiFreeDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SareesRoute: SareesRoute,
  ApiFreeDataRoute: ApiFreeDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
